version: '3.5'


x-zou-build: &zou-build
    image: zou:$ZOU_VERSION
    build:
        context: ./zou
        args:
            ZOU_VERSION: ${ZOU_VERSION}
            PREVIEW_FOLDER: ${PREVIEW_FOLDER}
            TMP_DIR: ${TMP_DIR}

services:
    kitsu:
        image: kitsu:$KITSU_VERSION
        build:
            context: ./kitsu
            args:
                KITSU_VERSION: ${KITSU_VERSION}

    zou-app:
        <<: *zou-build

    zou-event:
        <<: *zou-build
       
    zou-jobs:
        <<: *zou-build
