version: '3.5'

x-base: &base
    restart: always
    networks:
        - internal

x-env: &env
    env_file:
        - ${ENV_FILE}

x-zou-build: &zou-build
    image: zou:$ZOU_VERSION
    build:
        context: ./zou
        args:
            ZOU_VERSION: ${ZOU_VERSION}
            PREVIEW_FOLDER: ${PREVIEW_FOLDER}
            TMP_DIR: ${TMP_DIR}

services:
    kitsu:
        <<: *base
        <<: *env
        container_name: ${COMPOSE_PROJECT_NAME}-kitsu
        image: kitsu:$KITSU_VERSION
        environment:
          - ACME_AGREE=true
        build:
            context: ./kitsu
            args:
                KITSU_VERSION: ${KITSU_VERSION}
        links:
            - zou-app
        ports:
            - '${PORT}:80'

    zou-app:
        <<: *base
        <<: *env
        <<: *zou-build
        container_name: ${COMPOSE_PROJECT_NAME}-zou-app
        links:
            - db
            - zou-event
        volumes:
            - 'thumbnails:${PREVIEW_FOLDER}'
        command: "gunicorn --error-logfile - --access-logfile - -w 3 -k gevent -b :5000 zou.app:app"

    zou-event:
        <<: *base
        <<: *env
        <<: *zou-build
        container_name: ${COMPOSE_PROJECT_NAME}-zou-event
        links:
            - redis
        command: "gunicorn --error-logfile - --access-logfile - -w 1 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b :5001 zou.event_stream:app"

    db:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: postgres:9.5-alpine
        volumes:
            - 'db:/var/lib/postgresql/data'
        <<: *base

    redis:
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        image: redis:alpine
        volumes:
            - 'redis:/data'
        <<: *base

volumes:
    db:
        name: ${COMPOSE_PROJECT_NAME}-db
    redis:
        name: ${COMPOSE_PROJECT_NAME}-redis
    thumbnails:
        name: ${COMPOSE_PROJECT_NAME}-thumbnails

networks:
    internal:
        name: ${COMPOSE_PROJECT_NAME}-internal